# Trial

In [3]:
import requests
from bs4 import BeautifulSoup

# Define the URL of the page to scrape
url = "https://finance.yahoo.com/quote/%5EDJI/history/?period1=1401580800&period2=1717664113"

# Send a GET request to the URL
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Parse the HTML content
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Find the table container
    table_container = soup.find('div', class_='table-container')
    
    if table_container:
        # Find all rows in the table
        rows = table_container.find_all('tr', class_='svelte-ewueuo')
        
        # Extract header data
        headers = [th.text.strip() for th in rows[0].find_all('th')]
        
        # Extract row data
        data = []
        for row in rows[1:]:
            cells = row.find_all('td')
            row_data = [cell.text.strip() for cell in cells]
            data.append(row_data)
        
        # Print headers
        print(headers)
        
        # Print row data
        for row in data:
            print(row)
    else:
        print('Table container not found')
else:
    print(f'Failed to retrieve the page. Status code: {response.status_code}')

Failed to retrieve the page. Status code: 404

# Scraper

In [3]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service

from bs4 import BeautifulSoup
import time

# Set up the WebDriver
service = Service()
driver = webdriver.Chrome(service=service)
tickers=['%5EGSPC','%5EIXIC','MSFT','GOOGL','AMZN','NVDA', 'PYPL', 'SQ', 'V', 'MA', 'COIN', 'MSTR', 'RIOT', 'MARA', 'GC=F', 'SI=F']
# Define the URL of the page to scrape


url='https://finance.yahoo.com/quote/MSFT/history/?period1=1420070400&period2=1718101333'
# Navigate to the page

driver.get(url)


# Optionally wait for the page to fully load
time.sleep(5)

# Get the page source and close the WebDriver
html = driver.page_source
driver.quit()

# Parse the HTML content with BeautifulSoup
soup = BeautifulSoup(html, 'html.parser')

# Find the table container
table_container = soup.find('div', class_='table-container')

if table_container:
    # Find all rows in the table
    rows = table_container.find_all('tr', class_='svelte-ewueuo')
    
    # Extract header data
    headers = [th.text.strip() for th in rows[0].find_all('th')]
    
    # Extract row data
    data = []
    for row in rows[1:]:
        cells = row.find_all('td')
        row_data = [cell.text.strip() for cell in cells]
        data.append(row_data)
    
    # Create DataFrame
    df = pd.DataFrame(data, columns=headers)
        
    
    
else:
    print('Table container not found')

In [5]:
df

,Date,Open,High,Low,Close Close price adjusted for splits.,Adj Close Adjusted close price adjusted for splits and dividend and/or capital gain distributions.,Volume
0,"Jun 10, 2024",424.70,428.08,423.89,427.87,427.87,"14,003,000"
1,"Jun 7, 2024",426.20,426.28,423.00,423.85,423.85,"13,621,700"
2,"Jun 6, 2024",424.01,425.31,420.58,424.52,424.52,"14,861,300"
3,"Jun 5, 2024",417.81,424.08,416.30,424.01,424.01,"16,988,000"
4,"Jun 4, 2024",412.43,416.44,409.68,416.07,416.07,"14,348,900"
...,...,...,...,...,...,...,...
2408,"Jan 8, 2015",46.75,47.75,46.72,47.59,41.02,"29,645,200"
2409,"Jan 7, 2015",45.98,46.46,45.49,46.23,39.85,"29,114,100"
2410,"Jan 6, 2015",46.38,46.75,45.54,45.65,39.35,"36,447,900"
2411,"Jan 5, 2015",46.37,46.73,46.25,46.33,39.93,"39,673,900"
2412,"Jan 2, 2015",46.66,47.42,46.54,46.76,40.31,"27,913,900"

In [6]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from bs4 import BeautifulSoup
import time

# Set up the WebDriver

driver = webdriver.Chrome()
tickers = ['%5EGSPC', '%5EIXIC', 'MSFT', 'GOOGL', 'AMZN', 'NVDA', 'PYPL', 'SQ', 'V', 'MA', 'COIN', 'MSTR', 'RIOT', 'MARA', 'GC=F', 'SI=F']

# Initialize an empty list to store DataFrames
all_data = []

# Loop through each ticker
for ticker in tickers:
    url = f'https://finance.yahoo.com/quote/{ticker}/history/?period1=1420070400&period2=1718101333'
    try:
        driver.get(url)
        # Optionally wait for the page to fully load
        time.sleep(10)

        # Get the page source
        html = driver.page_source

        # Parse the HTML content with BeautifulSoup
        soup = BeautifulSoup(html, 'html.parser')

       
        # Find the table container
        table_container = soup.find('div', class_='table-container')

        if table_container:
            # Find all rows in the table
            rows = table_container.find_all('tr', class_='svelte-ewueuo')

            # Extract header data
            headers = [th.text.strip() for th in rows[0].find_all('th')]

            # Extract row data
            data = []
            for row in rows[1:]:
                cells = row.find_all('td')
                row_data = [cell.text.strip() for cell in cells]
                if row_data:  # Only add rows with data
                    data.append(row_data)

            # Create DataFrame
            df = pd.DataFrame(data, columns=headers)
            df['Ticker'] = ticker  # Add a column for the ticker symbol

            # Append the DataFrame to the list
            all_data.append(df)
        else:
            print(f'Table container not found for {ticker}')
    except Exception as e:
        print(f"URL not working for {ticker}. Error: {e}")

# Close the WebDriver after the loop
driver.quit()

# Concatenate all DataFrames into one
final_df = pd.concat(all_data, ignore_index=True)

# Print the final DataFrame
print(final_df)

               Date      Open      High       Low  \
0      Jun 10, 2024  5,341.22  5,365.79  5,331.52
1       Jun 7, 2024  5,343.81  5,375.08  5,331.33
2       Jun 6, 2024  5,357.80  5,362.35  5,335.36
3       Jun 5, 2024  5,314.48  5,354.16  5,297.64
4       Jun 4, 2024  5,278.24  5,298.80  5,257.63
...             ...       ...       ...       ...
35912   Jan 8, 2015    16.351    16.351    16.351
35913   Jan 7, 2015    16.480    16.550    16.480
35914   Jan 6, 2015    16.603    16.603    16.603
35915   Jan 5, 2015    16.179    16.179    16.179
35916   Jan 2, 2015    15.790    15.815    15.535

      Close    Close price adjusted for splits.  \
0                                      5,360.79
1                                      5,346.99
2                                      5,352.96
3                                      5,354.03
4                                      5,291.34
...                                         ...
35912                                    16.351
35913                                    16.510
35914                                    16.603
35915                                    16.179
35916                                    15.734

      Adj Close    Adjusted close price adjusted for splits and dividend and/or capital gain distributions.  \
0                                               5,360.79
1                                               5,346.99
2                                               5,352.96
3                                               5,354.03
4                                               5,291.34
...                                                  ...
35912                                             16.351
35913                                             16.510
35914                                             16.603
35915                                             16.179
35916                                             15.734

              Volume   Ticker
0      3,622,280,000  %5EGSPC
1      3,692,760,000  %5EGSPC
2      3,609,990,000  %5EGSPC
3      3,591,460,000  %5EGSPC
4      3,707,900,000  %5EGSPC
...              ...      ...
35912              -     SI=F
35913              9     SI=F
35914              2     SI=F
35915              -     SI=F
35916             13     SI=F

[35917 rows x 8 columns]

In [9]:
final_df.to_csv(r"D:\DATA SCIENCE\Internship\CrypoDataAnalysis\Scraped_Stock_Close_prices.csv")